version: '3'

services:
  bachelormodelviewcontroller:
    image: bachelormodelviewcontroller
    build:
      context: ./BachelorModelViewController
      dockerfile: Dockerfile

  webapplication1:
    image: webapplication1
    build:
      context: ./WebApplication1
      dockerfile: Dockerfile
