version: '2'
services:
  bachelormodelviewcontroller:
    image: bachelormodelviewcontroller
    links:
      - db
      - mongo
    environment:
      ConnectionStrings__Dataconnection: "Host=db;Username=admin;Password=admin123;Database=cupid"
      ConnectionStrings__Mongoconnection: "mongodb://mongo"
    ports:
      - "8000:80"
    build:
      context: ./BachelorModelViewController
      dockerfile: Dockerfile
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: cupid
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "31337:5432"
    volumes:
      - db-postgres:/var/lib/postgresql/data/pgdata:Z
  mongo:
    image: "mongo:3.4.1"
    ports:
      - "27017:27017"
    volumes:
      - db-mongo:/data/db:Z

volumes:
  db-postgres:
    external: true
  db-mongo:
    external: true
